theme: hugo-initio
defaultContentLanguage: de
pluralizeListTitles: false

taxonomies:
  klasse: klassen
  jahr: jahre

permalinks:
  beiträge: /:section/:year/:month/:title/
  kinder: /:section/:title
  schule: /:section/:title
  lehrer: /:section/:title
  eltern: /:section/:title
  verein: /:section/:title
  /: /:section/:title/

params:
  name: Förderverein der Thalia Grundschule
  year: 2022
  avatar: images/thalia-vf-logo.png
  avatarclass: circle
  background: ''
  banner: images/kinder.png
  favicon: images/gt_favicon.png
  DateForm: 'January 2, 2006'
  author: Sergey Pozhilov (GetTemplate.com)
  showSubheader: true
  showServices: true
  showRecentWorks: true
  showDownloads: true
  showClients: true
  showFooterContact: true
  showFooterFollowMe: true
  showFooterTextWidget: true
  showFooterFormWidget: true
  disqus:
    site: hugo-initio-site.disqus.com
  sharethis:
    property: '123456789012345678901234'
    custom: true
  google:
    analytics:
      trackerID: GA-000000000-0
  social:
    - title: facebook
      url: 'https://www.facebook.com/nickname'
      icon: fab fa-facebook-square
      footer: true
      sharethis: true
      network: facebook
    - title: twitter
      url: 'https://twitter.com/nickname'
      icon: fab fa-twitter-square
      footer: true
      sharethis: true
      network: twitter
    - title: instagram
      url: 'https://www.instagram.com/nickname'
      icon: fab fa-instagram
      footer: true
      sharethis: false
      network: ''
    - title: google+
      url: 'https://plus.google.com/+nickname'
      icon: fab fa-google-plus-square
      footer: false
      sharethis: true
      network: googleplus
    - title: linkedin
      url: 'https://www.linkedin.com/in/nickname'
      icon: fab fa-linkedin
      footer: false
      sharethis: true
      network: linkedin
    - title: tumblr
      url: 'https://nickname.tumblr.com'
      icon: fab fa-tumblr-square
      footer: false
      sharethis: false
      network: tumblr
    - title: github
      url: 'https://github.com/nickname'
      icon: fab fa-github
      footer: true
      sharethis: false
      network: ''
    - title: email
      url: 'mailto:some.email@somewhere.com'
      icon: fas fa-envelope-square
      footer: false
      sharethis: true
      network: email

